spring:
  profiles:
    active: dev
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 8080
  servlet:
    context-path: /

mybatis:
    type-aliases-package: com.founder.interservice.model
    mapper-locations: classpath:mybatis/mapper/*.xml
    config-location: classpath:mybatis/mybatis-config.xml
#  redis:
#    host:
#    port:

# 系统变量
xdhbigdata:
  xdhserviceParam:
    bizCode: XDH002
    cjServiceId: XDHDS0004
    getCjDataServiceId: XDHWS0022
wabigdata:
  objectrelation:
    url:  http://www.adu.cq:6080/api?name=objectRelation&key=62bf1b59c14bf770ccbc48767db26c48
  gettrack:
    url:  http://www.adu.cq:6080/api?name=getTrack&key=62bf1b59c14bf770ccbc48767db26c48
  relationGetAll:
    url:  http://www.adu.cq:6080/api?name=relationGetAll&key=62bf1b59c14bf770ccbc48767db26c48
  pgis:
    url:  http://77.1.24.49:8080/lbs/poiController/poiMarkers
  pgis_title:
    url:  http://77.1.24.49:8080/lbs?flag=search&jdObj=&wdObj=&inputFlag=&saveFlag=
#区域碰撞  相关的url
  regionalAnalysisTask:  #提交任务
    url:  http://www.adu.cq:6080/api?name=regionalAnalysisTask&key=62bf1b59c14bf770ccbc48767db26c48
  regionalAnalysisTaskStatus:  #获取任务状态
    url:  http://www.adu.cq:6080/api?name=regionalAnalysisTaskStatus&key=62bf1b59c14bf770ccbc48767db26c48
  regionalAnalysisTaskInfo:  #获取任务结果
    url:  http://www.adu.cq:6080/api?name=regionalAnalysisTaskInfo&key=62bf1b59c14bf770ccbc48767db26c48
#IMSI伴随 相关的url
  trackTravelTogetherForPhoneTask: #提交任务
    url:  http://www.adu.cq:6080/api?name=trackTravelTogetherForPhoneTask&key=62bf1b59c14bf770ccbc48767db26c48
  trackTravelTogetherForPhoneTaskStatus: #查询任务状态
    url:  http://www.adu.cq:6080/api?name=trackTravelTogetherForPhoneTaskStatus&key=62bf1b59c14bf770ccbc48767db26c48
  trackTravelTogetherForPhoneTaskInfo: #获取任务数据
    url:  http://www.adu.cq:6080/api?name=trackTravelTogetherForPhoneTaskInfo&key=62bf1b59c14bf770ccbc48767db26c48
#mysql sql打印
logging:
  level:
    com.founder.interservice.mapper : trace
    com.founder.interservice.regionalanalysis.mapper: trace
    com.founder.interservice.tracktraveltogether.mapper: trace