spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: XZXT
    password: XZXT
    url: jdbc:oracle:thin:@77.1.24.50:1521:xzxt
  #配置jpa 使其展示sql语句
  jpa:
    show-sql: false