server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: XZXT
    password: XZXT
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
  #配置jpa 使其展示sql语句
  jpa:
    show-sql: true
#mybatis:
#    type-aliases-package: com.founder.interservice.model
#    mapper-locations: classpath:mybatis/mapper/*.xml
#    config-location: classpath:mybatis/mybatis-config.xml
#  redis:
#    host:
#    port:
wabigdata:
  objectrelation:
    url:  http://www.adu.cq:6080/api?name=objectRelation&key=62bf1b59c14bf770ccbc48767db26c48
  gettrack:
    url:  http://www.adu.cq:6080/api?name=getTrack&key=62bf1b59c14bf770ccbc48767db26c48