spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: XZXT
    password: XZXT
    url: jdbc:oracle:thin:@192.168.1.147:1521:orcl
  #配置jpa 使其展示sql语句
  jpa:
    show-sql: false