spring:
  profiles:
    active: prod
server:
  port: 8080
  servlet:
    context-path: /
#mybatis:
#    type-aliases-package: com.founder.interservice.model
#    mapper-locations: classpath:mybatis/mapper/*.xml
#    config-location: classpath:mybatis/mybatis-config.xml
#  redis:
#    host:
#    port:
wabigdata:
  objectrelation:
    url:  http://www.adu.cq:6080/api?name=objectRelation&key=62bf1b59c14bf770ccbc48767db26c48
  gettrack:
    url:  http://www.adu.cq:6080/api?name=getTrack&key=62bf1b59c14bf770ccbc48767db26c48