spring:
  profiles:
    active: dev
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 8080
  servlet:
    context-path: /

mybatis:
    type-aliases-package: com.founder.interservice.model
    #mapper-locations: classpath:mybatis/mapper/*.xml
    config-location: classpath:mybatis/mybatis-config.xml
#  redis:
#    host:
#    port:

gab_url:
  ip: 10.172.20.13:9002
  #请求方地址
  senderId: C00-10001940
  #asj-服务方地址
  receiverAsjId: S10-10005788
  #fzxyr-4.10全国刑侦案事件犯罪嫌疑人信息查询服务
  receiverFzxyrId: S10-10005787
  #xzgzry-全国刑侦高危人员信息查询服务
  receiverXzgzryId: S10-10005784
  #ztryxx-全国在逃人员信息查询服务
  receiverZtryxxId: S10-10005794
  #cxztryxx-全国撤销在逃人员信息查询服务
  receiverCxztryxxId: S10-10005793

abutment_config:
  senderId: C51-00000017
  serviceId: S10-10005902
  userCardId: 510902198504188878
  userDept: 510996440000
  url: http://10.64.1.116:8585/node

# 系统变量
xdhbigdata:
  xdhserviceParam:
    bizCode: XDH002
    cjServiceId: XDHDS0004
    getCjDataServiceId: XDHWS0022
wabigdata:
  objectrelation:
    url:  http://www.adu.cq:6080/api?name=objectRelation&key=62bf1b59c14bf770ccbc48767db26c48
  gettrack:
    url:  http://www.adu.cq:6080/api?name=getTrack&key=62bf1b59c14bf770ccbc48767db26c48
  relationGetAll:
    url:  http://www.adu.cq:6080/api?name=relationGetAll&key=62bf1b59c14bf770ccbc48767db26c48
  pgis:
    url:  http://77.1.24.49:8080/lbs/poiController/poiMarkers
  pgis_title:
    url:  http://77.1.24.49:8080/lbs?flag=search&jdObj=&wdObj=&inputFlag=&saveFlag=
#区域碰撞  相关的url
  regionalAnalysisTask:  #提交任务
    url:  http://www.adu.cq:6080/api?name=regionalAnalysisTask&key=62bf1b59c14bf770ccbc48767db26c48
  regionalAnalysisTaskStatus:  #获取任务状态
    url:  http://www.adu.cq:6080/api?name=regionalAnalysisTaskStatus&key=62bf1b59c14bf770ccbc48767db26c48
  regionalAnalysisTaskInfo:  #获取任务结果
    url:  http://www.adu.cq:6080/api?name=regionalAnalysisTaskInfo&key=62bf1b59c14bf770ccbc48767db26c48
#IMSI伴随 相关的url
  trackTravelTogetherForPhoneTask: #提交任务
    url:  http://www.adu.cq:6080/api?name=trackTravelTogetherForPhoneTask&key=62bf1b59c14bf770ccbc48767db26c48
  trackTravelTogetherForPhoneTaskStatus: #查询任务状态
    url:  http://www.adu.cq:6080/api?name=trackTravelTogetherForPhoneTaskStatus&key=62bf1b59c14bf770ccbc48767db26c48
  trackTravelTogetherForPhoneTaskInfo: #获取任务数据
    url:  http://www.adu.cq:6080/api?name=trackTravelTogetherForPhoneTaskInfo&key=62bf1b59c14bf770ccbc48767db26c48
#mysql sql打印
logging:
  level:
    com.founder.interservice.mapper : trace
    com.founder.interservice.regionalanalysis.mapper: trace
    com.founder.interservice.tracktraveltogether.mapper: trace
    com.founder.interservice.recordLog.mapper: trace