spring:
  datasource:
    xzxt:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      username: XZXT
      password: XZXT
      url: jdbc:oracle:thin:@192.168.1.101:1521:cqxzxtsid
    gxzxt:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      username: XZXT
      password: XZXT
      url: jdbc:oracle:thin:@192.168.1.101:1521:cqxzxtsid
  #配置jpa 使其展示sql语句
  jpa:
    show-sql: true
